pipeline {  
  environment {
    registry = "cloudgeek007/devopspipeline"
    registryCredential = 'dockerhub'    
  }  
  agent any  
  stages {
    stage('Checkout'){
      steps {
        checkout scm
      }
    }
    stage('Building image') {
      steps{
        script {
          imageName = registry + ":$BUILD_NUMBER"
          context = "'./Day 2/Lab 03 - Part 1 - Containerising an App'"  
          dockerImage = docker.build(imageName, context)
        }
      }
    }
    stage ("Publish"){
      steps {
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            dockerImage.push("latest")
          }      
        }
      }
    }
    stage('Cleanup') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }
    stage('Deploy') {
      agent { label 'dockerwindows' } 
       steps{
        sh "docker stop app1"
        sh "docker rm -f app1"
        sh "docker run -d -p 5000:5000 --name app1 ${registry}:${BUILD_NUMBER}  "
      }
    }  
  }
}
